module.exports.dependencies = [
  "axios",
  "body-parser",
  "cors",
  "express",
  "jquery",
  "knex",
  "pg",
  "react",
  "react-dom",
  "semantic-ui-react",
  "babel-core",
  "babel-loader",
  "babel-preset-es2015",
  "babel-preset-react",
  "nodemon",
  "webpack",
  "helmet"
];
